import zapiLogo from './zapi-logo.png'
import apihub from './apihub.png'
import apihubbox from './apihubbox.png'
import login2 from './login2.png'
import otp from './otp.png'
import request from './request_edit.png'
import signup from './signup.png'
import subscriptions1 from './subscriptions1.png'
import subscriptions2 from './subscriptions2.png'
import uploadapi from './uploadapi.png'
export { zapiLogo , apihub , apihubbox , login2 , otp , request , signup , subscriptions1 , subscriptions2, uploadapi }