import facebook from './facebook.svg'
import figma from './figma.svg'
import google from './google.svg'
import heroBig from './hero-desktop.svg'
import heroMedium from './hero-tablet.svg'
import heroSmall from './hero-mobile.svg'
import heroIllustration from './hero-illustration.svg'
import ibm from './ibm.svg'
import microsoft from './microsoft.svg'
import zapi from './zapi.svg'
import cmLearningAPI from './cmLearningAPI.svg'
import compVisionAPI from './compVisionAPI.svg'
import natLangAPI from './natLangAPI.svg'
import chevron from './chevron.svg'
import dollars from './dollars.svg'
import pencil from './pencil.svg'
import secure from './secure.svg'
import stacks from './stacks.svg'
import zoom from './zoom.svg'
import marketIllustration from './marketIllustration.svg'

export { facebook, figma, google, heroBig, heroIllustration, heroMedium, heroSmall, ibm, microsoft, 
    zapi, cmLearningAPI, compVisionAPI, natLangAPI, chevron, stacks, secure, pencil, zoom, dollars, marketIllustration }